insert into search values (1, shippers, " 1 Shipping Company A None None None None None None None None 123 Any Street Memphis TN 99999 USA None None  0.00364604");
insert into search values (2, shippers, " 2 Shipping Company B None None None None None None None None 123 Any Street Memphis TN 99999 USA None None  0.00744136");
insert into search values (3, shippers, " 3 Shipping Company C None None None None None None None None 123 Any Street Memphis TN 99999 USA None None  0.00699126");
insert into search values (1, suppliers, " 1 Supplier A Andersen Elizabeth A. None Sales Manager None None None None None None None None None None None  0.00370964");
insert into search values (2, suppliers, " 2 Supplier B Weiler Cornelia None Sales Manager None None None None None None None None None None None  0.00400696");
insert into search values (3, suppliers, " 3 Supplier C Kelley Madeleine None Sales Representative None None None None None None None None None None None  0.000791923");
insert into search values (4, suppliers, " 4 Supplier D Sato Naoki None Marketing Manager None None None None None None None None None None None  0.000856949");
insert into search values (5, suppliers, " 5 Supplier E Hernandez-Echevarria Amaya None Sales Manager None None None None None None None None None None None  0.00169838");
insert into search values (6, suppliers, " 6 Supplier F Hayakawa Satomi None Marketing Assistant None None None None None None None None None None None  0.00175373");
insert into search values (7, suppliers, " 7 Supplier G Glasson Stuart None Marketing Manager None None None None None None None None None None None  0.000901698");
insert into search values (8, suppliers, " 8 Supplier H Dunton Bryn Paul None Sales Representative None None None None None None None None None None None  0.00134776");
insert into search values (9, suppliers, " 9 Supplier I Sandberg Mikael None Sales Manager None None None None None None None None None None None  None");
insert into search values (10, suppliers, " 10 Supplier J Sousa Luis None Sales Manager None None None None None None None None None None None  None");
